include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # since this library is full of math calculations,
    # I think it is better to be strict about types.
    omit_local_variable_types: false
