name: shamsi_date
description: >
  A Flutter package for using Jalali (Shamsi, Solar, Persian or Jalaali) calendar.
  You can convert, format and manipulate Jalali and Gregorian (Miladi) dates.
version: 0.10.0-nullsafety
homepage: https://github.com/FatulM/shamsi_date

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
