name: shamsi_date
description: >
  A Flutter package for using Jalali (Shamsi, Solar or Persian) date.
  You can convert, format and manipulate Jalali and Georgian dates.
version: 0.9.0
homepage: https://github.com/FatulM/shamsi_date

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
